enhancement: Add logger keyword argument to Consumer and Producer
benbenbang/types-confluent-kafka pull request #163
Opened 2024-01-30 14:06 UTC by jhominal

### **Description:**

Add `logger` keyword argument to `Consumer` and `Producer`

This argument is documented on the [official documentation page](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#kafka-client-configuration):

> `logger=logging.Handler` kwarg: forward logs from the Kafka client to the provided `logging.Handler` instance. To avoid spontaneous calls from non-Python threads the log messages will only be forwarded when `client.poll()` or `producer.flush()` are called. For example:
> ```python
> mylogger = logging.getLogger()
> mylogger.addHandler(logging.StreamHandler())
> producer = confluent_kafka.Producer({'bootstrap.servers': 'mybroker.com'}, logger=mylogger)
> ```

The presence of this argument is also corroborated by the function in the [source code that handles the arguments](https://github.com/confluentinc/confluent-kafka-python/blob/5a87879681d28375a55203c4839338b13b668046/src/confluent_kafka/src/confluent_kafka.c#L2229-L2232):

> ```c
>         /* Supported parameter constellations:
>          *  - kwargs (conf={..}, logger=..)
>          *  - args and kwargs ({..}, logger=..)
>          *  - args ({..})

### **Type of change**:

Please delete options that are not relevant.

- [x] New feature / Refactor / Enhancement (non-breaking change which adds new typings)

### **Checklist:**

- [ ] All code follows the project's coding style and conventions.
- [x] I have performed a self-review of my own code.
- [ ] My changes generate no new warnings or errors.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding updates to the documentation.

2024-01-31 12:26 UTC, exhuma requested changes

2024-01-31 12:26 UTC, exhuma commented on confluent_kafka-stubs/cimpl.pyi
> +    def __init__(self, config: dict[str, Any], *, logger: logging.Handler = ...) -> None: ...
Shouldn't this be `logging.Logger`?

2024-01-31 12:26 UTC, exhuma commented on confluent_kafka-stubs/cimpl.pyi
> +    def __init__(self, config: dict[str, Any], *, logger: logging.Handler = ...) -> None: ...
Shouldn't this be `logging.Logger`?

2024-01-31 20:01 UTC, benbenbang commented
Thanks for the PR @jhominal

2024-01-31 20:11 UTC, benbenbang commented on confluent_kafka-stubs/cimpl.pyi
> +    def __init__(self, config: dict[str, Any], *, logger: logging.Handler = ...) -> None: ...
This is very confusing from the confluent docs (as usual :(

- `logger` from their documentation is indeed 
> logger=logging.Handler kwarg: forward logs from the Kafka client to the provided logging.Handler instance. To avoid spontaneous calls from non-Python threads the log messages will only be forwarded when client.poll() or producer.flush() are called. For example: ...
- on the producer & consumer [docs](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Producer.Producer), we can see there's only `config`. Just want to confirm whether passing `logger` would work or not.

2024-01-31 23:07 UTC, jhominal commented on confluent_kafka-stubs/cimpl.pyi
> +    def __init__(self, config: dict[str, Any], *, logger: logging.Handler = ...) -> None: ...
* Yes, it should be documented as a `logging.Logger` - I made the PR in kind of a hurry, and I did not check that `logging.getLogger` does not return a `logging.Handler` instance (another fix that I will propose to the `confluent-kafka` doc);
 * Yes, passing a `logger` kwarg works, I am using that in production on both `Consumer` and `Producer` instances;
 * The truth, such as it is, requires delving into the implementation:
   * The actually implemented argument convention of [`common_conf_setup`](https://github.com/confluentinc/confluent-kafka-python/blob/5a87879681d28375a55203c4839338b13b668046/src/confluent_kafka/src/confluent_kafka.c#L2212) (which implements the argument parsing for both `Producer` and `Consumer`'s initializers) is a bit puzzling: it merges a positional dictionary given as a first argument with any `kwargs`, meaning that:
     * Even though it is not documented at all, it seems that every kafka config key could be passed as a keyword argument;
     * Even though `logger` is explicitly documented as a keyword argument, it seems that it would work if it was passed as a `logger` key in the `config` dictionary;
   * The only method call that `confluent-kafka` makes on the `logger` object is for a method called `log`, called with 5 positional arguments, the first being an `int`, and the next 4 being `str` - among objects documented in the `logging` module, only `logging.Logger` matches that description;

2024-01-31 23:18 UTC, jhominal commented on confluent_kafka-stubs/cimpl.pyi
> +    def __init__(self, config: dict[str, Any], *, logger: logging.Handler = ...) -> None: ...
After reviewing the documentation of `logging`, I can see that `logging.LoggerAdapter` also has a `log` method that fulfills the above criteria, so it would also make sense to type the `logger` argument as `logging.Logger | logging.LoggerAdapter`. What do you think?

2024-02-01 07:10 UTC, benbenbang commented
For the title, please check [here](https://github.com/benbenbang/types-confluent-kafka/blob/6248ab77e1b595b2d403db112fe1d50ffe451f01/.pre-commit-config.yaml#L53)

2024-02-01 10:03 UTC, exhuma commented on confluent_kafka-stubs/cimpl.pyi
> +    def __init__(self, config: dict[str, Any], *, logger: logging.Handler = ...) -> None: ...
So far, in my usages of the library I always used a Logger instance without issues. Similar to the following:

```python
import logging 

kafka_logger = logging.getLogger("kafka")
producer = Producer(..., logger=kafka_logger)
```

This always worked without issues.

I believe it's better to use a "Logger" instance here as this provides the biggest flexibility. For example the way filters are applied in the Python logging-framework is different depending on it being attached to a logger or a handler. These are small details, but I *assume* that the internal behaviour of the kafka library uses the object with the *intent* of scheduling a log message. And that's done on a logger, not a handler.

As you mention, the only call uses the "log" method. Which sounds very much like the expected intent.

Note that I don't have extensive experience with the library. But over 15 years of Python experience. So what I say above is based on Python experience. Not on kafka experience.

2024-02-03 07:41 UTC, benbenbang commented on confluent_kafka-stubs/cimpl.pyi
> +    def __init__(self, config: dict[str, Any], *, logger: logging.Handler = ...) -> None: ...
Please fix the CI Test as well

2024-02-03 07:41 UTC, benbenbang commented on confluent_kafka-stubs/cimpl.pyi
> +    def __init__(self, config: dict[str, Any], *, logger: logging.Handler = ...) -> None: ...
Please fix the CI Test as well

2024-02-05 22:06 UTC, jhominal commented
Sorry for being late to reply, I think that the PR should be good now.

2024-02-07 20:33 UTC, benbenbang commented
hello @jhominal 

seems like Github still doesn't fix the PR title frozen issue
can you please try:
```
git commit --allow-empty -m "ci: empty commit"
```
and trigger the CI by updating the SHA please

2024-02-08 07:03 UTC, merged

2024-02-08 07:12 UTC, ptah-lgtm commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/benbenbang/types-confluent-kafka/releases/tag/1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-08 07:14 UTC, benbenbang commented
thanks again @jhominal and @exhuma , new version is available now